In [1]:
import numpy as np
from sklearn.neighbors import LocalOutlierFactor
import pandas as pd

In [41]:
train=pd.read_csv('C:/Users/Santiago Zubieta/Documents/2023-2/statistical/Proyecto/ProyectoSLDA/Classification/Preprocesamiento/TrainCsv.csv')
train.head()

,CODIGO_EMPRESA,FRACASO,B11,B12,B13,B14,B21,B22,B23,B24,...,B69,B610,B611,B612,B613,B81,B82,B83,B84,B85
0,321000370,0,-0.013263,-0.014149,-0.019776,-0.049727,0.051358,0.054788,0.076576,0.192552,...,0.297489,1.493572,1.255421,0.399751,0.016188,0.060745,0.177370,0.017284,0.016202,0.315473
1,321000978,0,-0.006326,-0.015651,-0.035168,-0.028201,0.014865,0.036778,0.082643,0.066270,...,0.130267,1.714751,0.601136,0.102969,-0.098457,0.000052,0.000052,0.000029,0.000012,0.000781
2,321002540,0,0.016539,0.017104,0.041653,0.029021,0.034651,0.035834,0.087266,0.060801,...,0.071542,1.896541,0.738551,0.374806,-0.117346,0.025741,0.025741,0.015171,0.014670,0.423366
3,321002656,0,-0.056264,-0.159556,-0.383810,-0.273080,0.011525,0.032684,0.078621,0.055938,...,0.440071,1.169690,0.464437,0.275579,0.025202,0.006529,0.007618,0.003815,0.001345,0.116712
4,321003051,1,-0.019537,-0.036464,-0.107610,-0.055153,-0.471426,-0.879894,-2.596663,-1.330865,...,0.015802,2.110823,0.547137,0.025350,-0.201182,0.146241,0.146241,0.096686,0.051802,-0.109884

In [42]:
varBasuras=['B11','B13','B14','B21','B23','B24','B46','B48',
            'B51','B52','B53','B54','B61','B62','B63','B64',
            'B65','B66','B67','B611','B85']
X=train.drop(columns=varBasuras)

X.shape

(1798, 21)

In [44]:

X=train.iloc[:,2:]
lof=LocalOutlierFactor(n_neighbors=5,contamination=0.05)
y_pred=lof.fit_predict(X)

In [39]:
X.head()

,B11,B12,B13,B14,B21,B22,B23,B24,B31,B32,...,B69,B610,B611,B612,B613,B81,B82,B83,B84,B85
0,-0.013263,-0.014149,-0.019776,-0.049727,0.051358,0.054788,0.076576,0.192552,0.097446,0.187087,...,0.297489,1.493572,1.255421,0.399751,0.016188,0.060745,0.177370,0.017284,0.016202,0.315473
1,-0.006326,-0.015651,-0.035168,-0.028201,0.014865,0.036778,0.082643,0.066270,0.554977,0.000000,...,0.130267,1.714751,0.601136,0.102969,-0.098457,0.000052,0.000052,0.000029,0.000012,0.000781
2,0.016539,0.017104,0.041653,0.029021,0.034651,0.035834,0.087266,0.060801,0.589369,0.000000,...,0.071542,1.896541,0.738551,0.374806,-0.117346,0.025741,0.025741,0.015171,0.014670,0.423366
3,-0.056264,-0.159556,-0.383810,-0.273080,0.011525,0.032684,0.078621,0.055938,0.500754,0.083530,...,0.440071,1.169690,0.464437,0.275579,0.025202,0.006529,0.007618,0.003815,0.001345,0.116712
4,-0.019537,-0.036464,-0.107610,-0.055153,-0.471426,-0.879894,-2.596663,-1.330865,0.661144,0.000000,...,0.015802,2.110823,0.547137,0.025350,-0.201182,0.146241,0.146241,0.096686,0.051802,-0.109884

In [45]:
outliers=train[y_pred==-1]
outliers

,CODIGO_EMPRESA,FRACASO,B11,B12,B13,B14,B21,B22,B23,B24,...,B69,B610,B611,B612,B613,B81,B82,B83,B84,B85
4,321003051,1,-0.019537,-0.036464,-0.107610,-0.055153,-0.471426,-0.879894,-2.596663,-1.330865,...,0.015802,2.110823,0.547137,0.025350,-0.201182,0.146241,0.146241,0.096686,0.051802,-0.109884
10,321004262,0,-0.197409,-0.402637,-1.394143,-0.566142,-0.023670,-0.048277,-0.167161,-0.067882,...,0.259212,1.016436,0.675780,0.329260,-0.023969,0.000277,0.000801,0.000197,0.000096,-0.004074
22,321010096,1,-0.022295,-0.036158,0.023137,-0.014109,-0.250489,-0.406237,0.259950,-0.158516,...,0.010815,0.173907,-4.479432,0.132541,-0.207046,0.006744,0.006744,0.017282,0.010656,-0.042542
24,321010632,0,-0.001122,-0.001996,-0.005703,-0.003070,0.023820,0.042369,0.121080,0.065176,...,0.008923,0.540519,0.332178,0.991380,0.072575,0.064011,0.122210,0.041612,0.023394,0.982116
27,321012171,0,-0.001166,-0.002599,-0.003953,-0.007584,0.000026,0.000058,0.000088,0.000168,...,0.029456,0.139886,-0.097972,0.275252,0.006120,0.061972,0.148879,0.021236,0.009531,367.904762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1665,351083493,0,-0.069764,-0.061519,-0.947337,-0.065791,-0.179449,-0.158240,-2.436759,-0.169229,...,0.031289,2.211899,0.791992,0.327569,-0.180410,0.000981,0.001442,0.000917,0.001040,-0.005796
1670,351083988,0,0.125671,0.049386,1.188152,0.051528,-0.004622,-0.001816,-0.043701,-0.001895,...,0.715034,9.648564,2.812548,-0.154948,-0.384629,0.000138,0.000215,0.000133,0.000338,-0.073026
1671,351084522,0,0.000364,0.000032,0.000076,0.000056,-0.718656,-0.064040,-0.150459,-0.111497,...,0.002526,9.878173,4.204460,0.485217,-0.650819,0.000517,0.000517,0.000297,0.003329,-0.004633
1705,351091507,0,-0.005072,-0.006264,-0.031321,-0.007830,0.243244,0.300392,1.502055,0.375484,...,0.039190,0.039190,-0.904233,0.769167,0.331426,0.000000,0.000000,0.000000,0.000000,0.000000
1731,351095685,0,-0.121342,-0.013606,-0.279323,-0.014303,0.003934,0.000441,0.009055,0.000464,...,0.028249,17.689540,16.637204,0.098489,-0.403904,0.000026,0.000410,0.000024,0.000217,0.055149

In [47]:
remover=outliers[outliers['FRACASO']==0]
remover

(65, 42)

In [55]:
filtrado=train[~train['CODIGO_EMPRESA'].isin(outliers['CODIGO_EMPRESA'])]
filtrado.shape

(1708, 42)

In [56]:
filtrado['FRACASO'].value_counts()

0    1663
1      45
Name: FRACASO, dtype: int64

In [54]:
filtrado.to_csv('sinOutliers.csv')

In [25]:
print(outliers['FRACASO'].value_counts())
print(train['FRACASO'].value_counts())

0    34
1    20
Name: FRACASO, dtype: int64
0    1728
1      70
Name: FRACASO, dtype: int64